# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machines',
            name='id',
        ),
        migrations.AlterField(
            model_name='machines',
            name='machine_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
