# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20161230_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='machine_state',
            field=models.BooleanField(default=False),
        ),
    ]
